version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  django:
    build: ./services
    depends_on:
      - elasticsearch
    command: ["bash", "startup.sh"]
    volumes:
      - ./services:/app/services
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=elasticsearch:9200
    links:
      - elasticsearch
  site:
    image: node:latest
    command: ["bash", "entrypoint.sh"]
    working_dir: /site
    volumes:
      - ./site:/app/site
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site/build:/var/www/site # maps site build inside nginx
    environment:
      - SERVICES_HOST=django:8000
    depends_on:
      - django

volumes:
  node-modules:
