version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  django:
    build: ./services
    depends_on:
      - elasticsearch
    command: ["bash", "startup.sh"]
    volumes:
      - ./services:/app/services
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=elasticsearch:9200
    links:
      - elasticsearch
  site:
    build: ./site
    command: ["npm", "start"]
    volumes:
      - ./site:/app/site
      - node-modules:/app/site/node_modules
    ports:
      - "3000:3000"
    environment:
      - SERVICES_HOST=django:8000
    depends_on:
      - django

volumes:
  node-modules:
